import Head from "next/head";

// axios
import axios from "axios";

// types
import { Video } from "@/typing";

// comp
import { NoResults, VideoCard } from "@/components";

interface IProps {
  videos: Video[];
}

export default function Home({ videos }: IProps) {
  return (
    <>
      <Head>
        <title>Tiktik | Home</title>
        <meta name="description" content="Generated by @nkjy" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col gap-10 videos h-full">
        {videos.length ? (
          videos.map((video: Video) => (
            <VideoCard post={video} key={video._id} />
          ))
        ) : (
          <NoResults text="No Videos" />
        )}
      </div>
    </>
  );
}

export const getServerSideProps = async ({
  query: { topic },
}: {
  query: { topic: string };
}) => {
  let response= null;

  if(topic){
    response = await axios.get(
      `${process.env.NEXT_PUBLIC_BASE_URL}/api/discover/${topic}`
    );
  }else {
    response = await axios.get(
      `${process.env.NEXT_PUBLIC_BASE_URL}/api/post`
    );
  }

  return {
    props: {
      videos: response.data,
    },
  };
};
