import Head from "next/head";

// axios
import axios from "axios";

export default function Home() {
  return (
    <>
      <Head>
        <title>Tiktik | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className="text-black">Hello World</h1>
      </div>
    </>
  );
}

export const getServerSideProps = async () => {
  const { data } = await axios.get(`http://localhost:3000/api/post`);
  console.log(data);

  return {
    props: {
      data: data,
    },
  };
};
